### PR TITLE
fix broken doc and roadmap link

### PR DESCRIPTION
**Pull request by akphi**

### CODE REVIEW

**Review by maoo — APPROVED** [review]
LGTM!

**Review by gs-bracej — APPROVED** [review]

**Comment by gs-bracej** [comment]
@maoo this can't be merged because cla check is still running. Can we tickle/retry it somehow?

**Comment by maoo** [comment]
@cla-bot[bot] check

**Comment by maoo** [comment]
@gs-bracej @akphi - seems that the bot got stuck for some reason; when that happens, shoot a message with `@cla-bot[bot] check` and the bot will be re-summoned. TY!

**Comment by gs-bracej** [comment]
Good trick to know, thanks!

**Pull request merged**
